---
#
# Playbook to Provision Random Traffic Jam Loopbacks for Devnet Create Sandbox
# Written by: Nick Thompson (@nsthompson)
# Copyright (C) 2020 World Wide Technology
# All Rights Reserved
#
# Usage:
# -- Provision First Pass of Random Loopback Interfaces
# ansible-playbook -i inventory provision_random_loopbacks.yml --tags="first"
# -- Provision Second Pass of Random Loopback Interfaces
# ansible-playbook -i inventory provision_random_loopbacks.yml --tags="second"
#

- hosts: trafficjam
  connection: local

  collections:
    - wwt.trafficjam

  tasks:
    - name: Load Variables
      include_vars:
        file: ips.yml
      tags:
        - always

    - name: Provision VRF_A Loopback Interfaces
      trafficjam_dummy_interfaces:
        host: "{{ ansible_host }}"
        state: present
        config:
          name: "Random_A.{{ my_idx_a }}"
          description: "VRF_A Loopback"
          vrf_id: 54
          v4_address: "{{ item }}"
      loop: "{{ (random_A_addresses | shuffle)[0:5] }}"
      loop_control:
        pause: 2
        index_var: my_idx_a
      tags:
        - first

    - name: Provision VRF_B Loopback Interfaces
      trafficjam_dummy_interfaces:
        host: "{{ ansible_host }}"
        state: present
        config:
          name: "Random_B.{{ my_idx_b }}"
          description: "VRF_B Loopback"
          vrf_id: 55
          v4_address: "{{ item }}"
      loop: "{{ (random_B_addresses | shuffle)[0:5] }}"
      loop_control:
        pause: 2
        index_var: my_idx_b
      tags:
        - first

    - name: Provision VRF_A Loopback Interfaces
      trafficjam_dummy_interfaces:
        host: "{{ ansible_host }}"
        state: present
        config:
          name: "Random_A2.{{ my_idx_a2 }}"
          description: "VRF_A Loopback"
          vrf_id: 54
          v4_address: "{{ item }}"
      loop: "{{ (random_A2_addresses | shuffle)[0:5] }}"
      loop_control:
        pause: 2
        index_var: my_idx_a2
      tags:
        - second

    - name: Provision VRF_B Loopback Interfaces
      trafficjam_dummy_interfaces:
        host: "{{ ansible_host }}"
        state: present
        config:
          name: "Random_B2.{{ my_idx_b2 }}"
          description: "VRF_B Loopback"
          vrf_id: 55
          v4_address: "{{ item }}"
      loop: "{{ (random_B2_addresses | shuffle)[0:5] }}"
      loop_control:
        pause: 2
        index_var: my_idx_b2
      tags:
        - second