---
# Requirements File for Devnet Create Sandbox
roles:
  - src: https://github.com/CiscoDevNet/ansible-pyats
    scm: git
    name: ansible-pyats

collections:
  - name: wwt.trafficjam
    version: 1.0.1
    source: https://galaxy.ansible.com 